---
- hosts: apach
  become: yes
    
  tasks:
  
# JAVA
  - name: Check java installed
    package:
        name: "java-1.8.0-openjdk"
        state: present

# APACHE
  - name: Install Apache.
    yum: name=httpd state=present

  - name: check Apache is up
    service: name=httpd state=started enabled=yes
 
 # NODE EXPORTER
  # - name: Install node exporter
  #   unarchive:
  #     src: "https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz"
  #     dest: /opt
  #     remote_src: yes 